### ISSUE TITLE
How to use for android

### ISSUE THREAD

**Issue by tunahanbayindir** [ypresto/qtfaststart-java#2]
I dont know how to use this library and I dont have much experience with FFmpeg.

I am running out of time because of my deadline.
Can you please prepare some guideliness.

Best regards,
Keep up the good work.

**Comment by ypresto** [comment]
``` java
    /**
     * @param in  Input file.
     * @param out Output file.
     * @return false if input file is already fast start.
     * @throws IOException
     */
    public static boolean fastStart(File in, File out) throws IOException, MalformedFileException, UnsupportedFileException {
```

That's all..!

**Comment by ypresto** [comment]
Note that if it returns false, use `in` file instead of `out` file.

**Comment by ypresto** [comment]
It is written in pure-java, so no additional dependency or setup is required for Android.

**Comment by ypresto** [comment]
> with FFmpeg

If you want to transcode (i.e. create video with smaller size), use [android-transcoder](https://github.com/ypresto/android-transcoder) and feed its output to this library.
Note that this library and android-transcoder are totally unrelated to FFmpeg.

**Comment by tunahanbayindir** [comment]
Thanks for ultimately fast reply :)

I did what you said before, but it says 2 out of 3 exceptions alredy catched (without compile).

Here is the code segment;

File f = new File(path);

```
        try{
            QtFastStart.fastStart(f, f);
        }catch (QtFastStart.QtFastStartException e){
            Log.e("QT", e.toString());
        }catch (QtFastStart.MalformedFileException m){ // catched
            Log.e("QT", m.toString());
        }catch (QtFastStart.UnsupportedFileException q){ // catched
            Log.e("QT", q.toString());
        }catch (IOException i){
            Log.e("QT", i.toString());
        }
```

path is the recorded video file's path.

**Comment by ypresto** [comment]
It is not library problem. You have Java compilation error.
It is because you catch `QtFastStartException` at first catch clause.
`QtFastStartException` is base class of `MalformedFileException` and `UnsupportedFileException`, so the catch clause of it should be placed after these two exceptions.

``` java
        }catch (QtFastStart.MalformedFileException m){
            Log.e("QT", m.toString());
        }catch (QtFastStart.UnsupportedFileException q){
            Log.e("QT", q.toString());
        }catch (QtFastStart.QtFastStartException e){ // catches QtFastStartException other than MalformedFileException and UnsupportedFileException
            Log.e("QT", e.toString());
```

**Comment by tunahanbayindir** [comment]
can't make it work.

debug results are;

ftypAtom: null,
startOffset: 0,
atomSize: 0,
atomType: 0

```
        printf("last atom in file was not a moov atom");
```

**Comment by tunahanbayindir** [comment]
I did it :))

Thanks for your help. I added you from LinkedIn - Tunahan Bayındır.
I have a few more questions if you can help me I'll really appreciate it.

Have a nice day!
